### ISSUE TITLE
چطور میشه در نقشه ثابت ایکون رو تغییر داد

### ISSUE THREAD

**Issue by iman100** [cedarstudios/cedarmaps-android-sdk#2]
من برای نمایش نقشه بر روی  یک اکتیویتی از نقشه ثابت استفاده کردم ولی برای نمایش ایکون در نقشه ثابت راه های مختلف رو امتحان کردم ولی ایکون رو  بازخوانی نمی کنه برای نمایش در نقشه
`    Uri resourceURI = Uri.parse("android.resource://" + this.getPackageName() + "/" + R.mipmap.ic_marker_shop);
`
یا 
`Uri resourceURI = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE +
      "://" + getResources().getResourcePackageName(R.mipmap.ic_marker_shop)
      + '/' + getResources().getResourceTypeName(R.mipmap.ic_marker_shop) + '/'
      + getResources().getResourceEntryName(R.mipmap.ic_marker_shop) );`

    markers.add(new StaticMarker(coordinate, resourceURI));
هیچ کدام ایکون مورد من در نقشه نمایش داده نمیشن

**Comment by sdtaheri** [comment]
مارکر نقشه استاتیک آدرس ریموت میخواد دیگه. نمیتونی از فایل سیستم خودش
بخونه.

**Comment by ghost** [comment]
این متد فقط با آدرس‌های ریموت (موجود در یک وب‌سرور) کار می‌کند.

**Comment by iman100** [comment]
@sdtaheri
 خوب من هم از ادرس ها رو از سرویس سرور خودمون دارم می خونم و با ای پی آی سیدارمپ نمایش می
 دهم فقط می خوام نقاط با آیکون کاستوم خودمون نمایش بده نه ایکون دیفالت

**Comment by ghost** [comment]
شِمای آدرس‌ها باید به صورت
http
و یا 
https
باشند.
در کدی که ارسال کرده‌اید چنین چیزی مشاهده نمی‌شود

این تصاویر در سمت سرور ساخته می‌شوند. به همین دلیل آدرس مارکر باید از طریق وب در دسترس باشد.
