### ISSUE TITLE
چگونگی نمایش نقاط اطراف شخص

### ISSUE THREAD

**Issue by iman100** [cedarstudios/cedarmaps-android-sdk#3]
آیا امکان نمایش نقاط نزذیک شخص برای او با استفاده از سیدارمپ وجود داره؟؟
توضیح: 
مثلا شخص بخواهد تاکسی ها اطراف رو از سرور بازخوانی کند وجود دارد و نیاز به بازخوانی تمامی نقاط از شهر یا آن استان نباشد؟؟؟

**Comment by mohsentaleb** [comment]
این قسمت در گیت هاب مخصوص مطرح کردن مشکلات برنامه نویسی است و سئوال شما مربوط به پیاده سازی قابلیتی است که به سادگی با داشتن دانش برنامه نویسی قابل حل است. لطفا سئوالات اینچینی را از طریق ایمیل برای ما ارسال کنید.
