### ISSUE TITLE
مشکل حذف یک مارکر 

### ISSUE THREAD

**Issue by comaliansoll** [cedarstudios/cedarmaps-android-sdk#4]
سلام 
من دوتا مارکر روی مپ در اندروید ادد می کنم  
و می خوام با کلید بک  مارکر آخر رو پاک کنم 
باید از چه متدی استفاده کنم ؟

**Comment by ghost** [comment]
با استفاده از مثال زیر میتوانید مارکر را در قالب یک لایه به نقشه اضافه کنید.
https://docs.mapbox.com/android/maps/examples/marker-symbol-layer/

برای حذف مارکر مد نظر می‌توانید لایه مربوط به آن را حذف کنید.
به مثال‌های متعدد موجود در آدرس فوق توجه بفرمایید.
