### ISSUE TITLE
Map doesn't move and change camera position

### ISSUE THREAD

**Issue by amir-ardalanuk** [cedarstudios/cedarmaps-android-sdk#5]
When we go to a new Fragment from the current fragment ( that contain map ) with 
 ```
val transaction = supportFragmentManager.beginTransaction()
transaction.add(containerId, fragment)
transaction.addToBackStack(tag)
transaction.commit()
```
the map in new fragment doesn't move camera 
please let me know how can i fix this issue

**Comment by ghost** [comment]
Having two maps in consequent fragments, which basically appear above each other is not a good practice.
However, as stated [here](https://blog.mapbox.com/asynchronous-rendering-on-android-831722ac1837) in a blog post from Mapbox, you can use TextureView instead of default SurfaceView.

> Although SurfaceView is very efficient, it might not fit all use cases as it creates a separate window and cannot be moved, transformed, or animated. For these situations where you need more flexibility, it’s usually best to use a TextureView. This is less performant than SurfaceView, but it behaves as a standard View and can be manipulated as such.

**Comment by sdtaheri** [comment]
This issue is closed due to inactivity.
