### ISSUE TITLE
آموزش امکانات سیدار مپ

### ISSUE THREAD

**Issue by RezaAlizadeh98** [cedarstudios/cedarmaps-android-sdk#6]
سلام خسته نباشید اگر میشه اموزش های کاربردی از سیدار مپ مثلا مکان یابیش و نقطه میانی رو اینجا با سورس کد اموزش بدین ممنون میشم...

**Comment by sdtaheri** [comment]
سلام. امکانات اولیه در اپلیکیشن دمو نمایش داده شده است. برای مشاهده مثال‌های بیشتر می‌توانید به [مثال‌های مپباکس](https://docs.mapbox.com/android/maps/examples/) مراجعه کنید.
