### ISSUE TITLE
not attached to a context error

### ISSUE THREAD

**Issue by makazemi** [cedarstudios/cedarmaps-android-sdk#7]
hello. I have an crash report on firebase crashlytichs that a lot has happened. 
Fragment MapFragment{b58ba5f} (b1fd863a-9f45-43c2-89b3-56630515cd86)} not attached to a context.
In normal test i don't catch it anymore and I don't know how it produce.

**Comment by sdtaheri** [comment]
Hello @makazemi,

This issue would arise in various situations. Please provide the code for the Fragment in which you used MapView and the Activity through which you're presenting the aforementioned Fragment.

**Comment by makazemi** [comment]
this is baseMapFragment: [baseMapFragment](https://paste.ubuntu.com/p/vXZFKHZtxB/)
this is BaseActivity: [BaseActivity](https://paste.ubuntu.com/p/3pX7cy7xCK/)
this is Parent activity: [MainActivity](https://paste.ubuntu.com/p/FpkyGXXpR7/)

**Comment by sdtaheri** [comment]
As indicated in [Mapbox documentation](https://docs.mapbox.com/android/maps/overview/#5-lifecycle-methods) as well as our own sample app, you should call all `MapView`'s lifecycle methods. 
You seem to have only called the `onCreate` method; furthermore, you're calling it in a wrong place. If you are using fragments, call it in fragment's `onCreate` or `onCreateView` or `onViewCreated` based on your needs.
I once again emphasize not to forget to call other lifecycle methods as they will help in issues related to garbage collection.

**Comment by makazemi** [comment]
Thanks. I call all mapView's lifecycle method. But I had a new problem. When my map fragment is pop back stack(press back button), it's view detach in a deformal state. It seem the map suddenly go away. This is an screen recorded of this state that i have explained. [screen record](https://drive.google.com/open?id=1Xmyt9julYq7CuMsCQts3o-spVjSoCSVn)

**Comment by sdtaheri** [comment]
I believe this is an implementation detail and it's not related to the issue this thread was based upon. 

Please check the order of calling stuff in your `onBackPressed` override. Take a look at stuff like `replace` and `add` in fragments. I can't help you specifically on this since it could be related to many different things.

If the main issue is fixed, let's close this.
