### ISSUE TITLE
ERROR: Unable to resolve dependency

### ISSUE THREAD

**Issue by hastitavakoli2020** [cedarstudios/cedarmaps-android-sdk#9]
Hi
I made a new Project with this config.
android studio 3.5.3
gradle 3.5.3

dependencies {
    `implementation fileTree(dir: 'libs', include: ['*.jar'])`
    `implementation 'androidx.appcompat:appcompat:1.0.2'`
   ` implementation 'androidx.constraintlayout:constraintlayout:1.1.3'`
    `testImplementation 'junit:junit:4.12'`
    `implementation 'com.cedarmaps:CedarMapsSDK:4.2.1'`
}

repositories {
        `jcenter()`
        `google()`
       ` jcenter()`
      `  maven {
            url "https://repo.cedarmaps.com/android/"
        }`
          }

and when i sync gradle , it can't sync.
This is my error.
`ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.cedarmaps:CedarMapsSDK:4.2.1.`
`Show Details`
`Affected Modules: app`

`ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.cedarmaps:CedarMapsSDK:4.2.1.`
`Show Details`
`Affected Modules: app`

`ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.cedarmaps:CedarMapsSDK:4.2.1.`
`Show Details`
`Affected Modules: app`

I use different way to solve this (like change proxy , change devices , change networks) but i can't.

please help me.

**Comment by prog47** [comment]
Hi
I have exactly same error.

what should we do?

thanks for any help

**Comment by sdtaheri** [comment]
Hello,

* Make sure you have put CedarMaps repository address in `allProjects` section and **NOT** in `buildscript` block.
* Make sure Gradle is not set to offline mode. You can consult [this answer](https://stackoverflow.com/a/30794890/3730881) in StackOverflow.
* Make sure Android Studio's internet connection is assumed to be out of Iran. You can confirm this by typing `curl ipinfo.io` in Android Studio's Terminal.
* Android Studio's proxy settings does not follow system's proxy settings. If you are not using a systemwide VPN, make sure to enter your proxy's credentials in Android Studio as well.
* Sometimes reopening Android Studio is needed after connecting to a VPN or proxy service.
* Sometimes clicking on `Restart/Invalidate Caches` would help.

Android Studio tries to download [this aar file](https://repo.cedarmaps.com/android/com/cedarmaps/CedarMapsSDK/4.2.1/CedarMapsSDK-4.2.1.aar). As you can see, this file is available to download. If you're getting an error indicating that this file can't be fetched or the dependency can't be resolved, it's related to one the items mentioned above.

If for any reason you couldn't make it work, you can download the aar file and add it to your project manually. You should bear in mind that in that case, adding CedarMaps dependencies would be your job.

**Comment by sdtaheri** [comment]
This issue would be closed because of inactivity.
